Repository chatchat-space/Langchain-Chatchat, pull requests merged in 2024-04, with the labels that each got.

#3585 Update README.md
  README.md
Labels: size:XS

#3591 解决ollama部署的qwen,执行agent,返回的json格式不正确问题。
  chatchat-server/chatchat/server/agent/agent_factory/qwen_agent.py
Labels: size:S

#3579 完成了 BootstrapWebBuilder加载用户配置，适配标准报文使用RESTFulOpenAIBootstrapBaseWeb完成业务，提供xinference 插件示例
  chatchat-server/pyproject.toml
  model-providers/model_providers.yaml
  model-providers/model_providers/__init__.py
  model-providers/model_providers/__main__.py
  model-providers/model_providers/bootstrap_web/common.py
  model-providers/model_providers/bootstrap_web/entities/__init__.py
  model-providers/model_providers/bootstrap_web/entities/model_provider_entities.py
  model-providers/model_providers/bootstrap_web/openai_bootstrap_web.py
  model-providers/model_providers/core/bootstrap/base.py
  model-providers/model_providers/core/bootstrap/openai_protocol.py
  model-providers/model_providers/core/entities/provider_configuration.py
  model-providers/model_providers/core/entities/provider_entities.py
  model-providers/model_providers/core/model_manager.py
  model-providers/model_providers/core/model_runtime/entities/message_entities.py
  model-providers/model_providers/core/model_runtime/entities/model_entities.py
  model-providers/model_providers/core/model_runtime/model_providers/model_provider_factory.py
  model-providers/model_providers/core/model_runtime/model_providers/xinference/llm/_position.yaml
  model-providers/model_providers/core/model_runtime/model_providers/xinference/llm/chatglm3-6b.yaml
  model-providers/model_providers/core/provider_manager.py
  model-providers/model_providers/core/utils/utils.py
  model-providers/pyproject.toml
  model-providers/tests/server_unit_test/conftest.py
  model-providers/tests/server_unit_test/test_init_server.py
  model-providers/tests/unit_test/conftest.py
  model-providers/tests/unit_test/test_provider_manager_models.py
Labels: size:XXL

#3625 兼容model_providers，集成webui及API中平台配置的初始化
  .gitignore
  chatchat-server/chatchat/configs/loom.yaml.example
  chatchat-server/chatchat/configs/model_config.py.example
  chatchat-server/chatchat/configs/model_providers.yaml.example
  chatchat-server/chatchat/configs/openai-plugins-list.json
  chatchat-server/chatchat/model_loaders/init_server.py
  chatchat-server/chatchat/server/utils.py
  chatchat-server/chatchat/startup.py
  chatchat-server/chatchat/webui_pages/loom_view_client.py
  chatchat-server/chatchat/webui_pages/openai_plugins/__init__.py
  chatchat-server/chatchat/webui_pages/openai_plugins/base.py
  chatchat-server/pyproject.toml
  chatchat-server/tests/unit_server/test_init_server.py
  model-providers/model_providers/__main__.py
  model-providers/model_providers/bootstrap_web/openai_bootstrap_web.py
  model-providers/model_providers/core/bootstrap/base.py
  model-providers/model_providers/core/bootstrap/providers_wapper.py
Labels: size:XXL

#3653 embedding convert endpoint
  model-providers/model_providers/__main__.py
  model-providers/model_providers/bootstrap_web/common.py
  model-providers/model_providers/bootstrap_web/message_convert/__init__.py
  model-providers/model_providers/bootstrap_web/message_convert/core.py
  model-providers/model_providers/bootstrap_web/openai_bootstrap_web.py
  model-providers/model_providers/core/bootstrap/providers_wapper.py
  model-providers/model_providers/core/model_runtime/model_providers/google/llm/llm.py
Labels: size:XL

#3664 Feat/docker v0.2.10
  README.md
  README_en.md
  README_ja.md
Labels: size:S

#3741 Feature/frontend knowledgebase
  frontend/src/app/knowledge/(desktop)/features/KnowledgeCard.tsx
  frontend/src/app/knowledge/(desktop)/features/KnowledgeList.tsx
  frontend/src/app/knowledge/(desktop)/features/ModalCreateKnowledge.tsx
  frontend/src/app/knowledge/(desktop)/index.tsx
  frontend/src/app/knowledge/(desktop)/layout.desktop.tsx
  frontend/src/app/knowledge/[id]/base/[fileId]/features/ModalSegment.tsx
  frontend/src/app/knowledge/[id]/base/[fileId]/page.tsx
  frontend/src/app/knowledge/[id]/base/features/ModalAddFile.tsx
  frontend/src/app/knowledge/[id]/base/page.tsx
  frontend/src/app/knowledge/[id]/config/page.tsx
  frontend/src/app/knowledge/[id]/layout.tsx
  frontend/src/app/knowledge/[id]/tabs/TabItem.tsx
  frontend/src/app/knowledge/[id]/tabs/index.tsx
  frontend/src/app/knowledge/page.tsx
  frontend/src/features/SideBar/TopActions.tsx
  frontend/src/store/global/slices/common/initialState.ts
Labels: size:XL

#3743 lobe 添加ChatChat-api 和 models
  frontend/.env.example
  frontend/src/app/api/chat/[provider]/agentRuntime.ts
  frontend/src/app/chat/features/SessionListContent/ListItem/index.tsx
  frontend/src/app/settings/(mobile)/features/Header/Home.tsx
  frontend/src/app/settings/llm/ChatChat/index.tsx
  frontend/src/app/settings/llm/index.tsx
  frontend/src/app/welcome/(mobile)/features/Header.tsx
  frontend/src/components/FullscreenLoading/index.tsx
  frontend/src/components/ModelIcon/index.tsx
  frontend/src/components/ModelProviderIcon/index.tsx
  frontend/src/config/modelProviders/chatchat.ts
  frontend/src/config/modelProviders/index.ts
  frontend/src/config/server/provider.ts
  frontend/src/const/settings.ts
  frontend/src/features/Conversation/Error/style.tsx
  frontend/src/libs/agent-runtime/chatchat/index.test.ts
  frontend/src/libs/agent-runtime/chatchat/index.ts
  frontend/src/libs/agent-runtime/error.ts
  frontend/src/libs/agent-runtime/index.ts
  frontend/src/libs/agent-runtime/types/type.ts
  frontend/src/locales/default/common.ts
  frontend/src/locales/default/setting.ts
  frontend/src/services/_auth.ts
  frontend/src/store/global/slices/settings/selectors/modelProvider.ts
  frontend/src/types/settings/modelProvider.ts
Labels: size:L

#3744 /v1/models 接口返回值由 List[Model] 改为 {'data': List[Model]}，兼容最新版 xinference
  chatchat-server/chatchat/server/api_server/openai_routes.py
Labels: size:S

#3670 fix: 以lite模式启动时仅加载了在线嵌入模型,未加载配置的默认嵌入模型,导致创建知识库时报错 'bge-large-zh-v1.5'…
  webui_pages/knowledge_base/knowledge_base.py
Labels: size:XS

#3458 修复获取reranker_model_path出错的问题
  server/chat/knowledge_base_chat.py
Labels: size:S

#3745 Feat/git action
  .dockerignore
  .github/workflows/docker-build.yaml
  Dockerfile
Labels: size:L

#3758 Feat/update actions
  .github/workflows/docker-build.yaml
Labels: size:S

#3574 support zhipu-api embedding
  server/model_workers/zhipu.py
Labels: size:S

#3340 Adding Claude 3 API support
  configs/model_config.py.example
  configs/server_config.py.example
  server/model_workers/__init__.py
  server/model_workers/claude.py
Labels: size:L

#3760 fix:fix model_config claude-api
  .github/workflows/docker-build.yaml
  configs/model_config.py.example
Labels: size:S

#3773 feat:support action update Readme
  .github/workflows/docker-build.yaml
  README.md
  README_en.md
  README_ja.md
Labels: size:S

#3779 Feat/action update readme
  .github/workflows/docker-build.yaml
Labels: size:XS

#3854 pip源仓库设置，一些版本问题，启动说明
  chatchat-server/README.md
  chatchat-server/pyproject.toml
  model-providers/pyproject.toml
  pyproject.toml
Labels: size:M

#3564 更新火山方舟调用
  configs/model_config.py.example
  requirements.txt
  requirements_api.txt
  requirements_lite.txt
  server/model_workers/fangzhou.py
Labels: size:M
