Repository chatchat-space/Langchain-Chatchat, pull requests merged in 2024-01, with the labels that each got.

#2520 fix: ApiRequest.agent_chat 应当返回 dict 而非 str
  webui_pages/utils.py
Labels: size:XS

#2523 fix: Chinese comma in requirements
  requirements_api.txt
  requirements_lite.txt
Labels: size:XS

#2525 增加 PDF_OCR_THRESHOLD 配置项，只对宽高超过页面一定比例（图片宽/页面宽，图片高/页面高）的图片进行 OCR。
  configs/kb_config.py.example
  document_loaders/mypdfloader.py
Labels: size:S

#2540 修复milvus_kwargs问题
  configs/kb_config.py.example
Labels: size:XS

#2564 fix: make_text_splitter use wrong chunk_* parameters when exception.
  server/knowledge_base/utils.py
Labels: size:XS

#2585 fix: 过滤 sse_starlette 返回的 ping 包，避免 `JSON Decoder error : ping -...`
  server/model_workers/minimax.py
  webui_pages/utils.py
Labels: size:XS

#2514 fix: automatically replace unsupported torch device
  server/utils.py
Labels: size:S

#2570 Fix device detection and fallback logic
  server/utils.py
Labels: size:M

#2599 删除重复的引入和纠正拼写错误
  init_database.py
  server/knowledge_base/migrate.py
  tests/test_migrate.py
Labels: size:S

#2627 0.2.x稳定依赖更新
  README.md
  README_en.md
  img/qr_code_82.jpg
  img/qr_code_83.jpg
  img/qr_code_84.jpg
  requirements.txt
  requirements_api.txt
  requirements_lite.txt
  requirements_webui.txt
Labels: size:L

#2630 Gemini api
  configs/model_config.py.example
  configs/server_config.py.example
  server/model_workers/__init__.py
  server/model_workers/gemini.py
Labels: size:L

#2591 Fix/pgvector connect
  server/knowledge_base/kb_service/pg_kb_service.py
Labels: size:M

#2013 【功能新增】增强对PPT、DOC知识库文件的OCR识别
  document_loaders/__init__.py
  document_loaders/mydocloader.py
  document_loaders/mypptloader.py
  server/knowledge_base/utils.py
  tests/samples/ocr_test.docx
  tests/samples/ocr_test.pptx
Labels: size:L

#2480 修改pg库：每次创建对象时从连接池获取连接，避免每次执行方法时都新建连接
  server/knowledge_base/kb_service/pg_kb_service.py
Labels: size:S

#2638 0.2.10 Agent更新
  configs/__init__.py
  embeddings/add_embedding_keywords.py
  requirements.txt
  requirements_api.txt
  requirements_lite.txt
  requirements_webui.txt
  server/agent/custom_agent/ChatGLM3Agent.py
  server/agent/model_contain.py
  server/agent/tools/__init__.py
  server/agent/tools/arxiv.yaml
  server/agent/tools/calculate.yaml
  server/agent/tools/search_internet.yaml
  server/agent/tools/search_knowledgebase_complex.yaml
  server/agent/tools/search_youtube.yaml
  server/agent/tools/shell.yaml
  server/agent/tools/weather_check.py
  server/agent/tools/weather_check.yaml
  server/agent/tools/wolfram.yaml
  server/agent/tools_select.py
  server/callback_handler/conversation_callback_handler.py
  server/chat/agent_chat.py
  server/chat/search_engine_chat.py
  webui_pages/utils.py
Labels: size:XXL

#2640 Update milvus_kb_service.py
  server/knowledge_base/kb_service/milvus_kb_service.py
Labels: size:XS

#2647 更新即将废弃的启动内容
  server/knowledge_base/utils.py
  server/static/swagger-ui-bundle.js
  startup.py
Labels: size:L

#2649 ChatOpenAI为了判断token有没有超过模型的context上下文长度，
  server/minx_chat_openai.py
  server/utils.py
Labels: size:L

#2648 Fix two bugs in Minimax's model worker that affect usage
  server/model_workers/minimax.py
Labels: size:XS

#2659 更新运行数据库报错和项目里程碑
  README.md
  README_en.md
  server/knowledge_base/kb_service/milvus_kb_service.py
Labels: size:S

#2681 修复bug-langchain新版本PGVector传入connection，插入、删除操作会回滚
  server/knowledge_base/kb_service/pg_kb_service.py
Labels: size:XS

#2688 fix:修复ES库无法向量检索.添加mappings创建向量索引
  server/knowledge_base/kb_service/es_kb_service.py
Labels: size:XS

#2704 1、ES库index_name获取兼容windows和linux系统 2、补充mappings,创建向量索引结构保持一致 3、添加ES测试方法
  server/knowledge_base/kb_service/es_kb_service.py
Labels: size:M

#2740 perf typing
  server/db/repository/knowledge_file_repository.py
  server/knowledge_base/kb_service/base.py
  server/knowledge_base/kb_service/faiss_kb_service.py
Labels: size:S

#2746 支持GLM4
  configs/model_config.py.example
  requirements.txt
  requirements_api.txt
  requirements_lite.txt
  server/agent/tools/weather_check.py
  server/knowledge_base/kb_service/milvus_kb_service.py
  server/knowledge_base/kb_service/zilliz_kb_service.py
  server/model_workers/gemini.py
  server/model_workers/qianfan.py
  server/model_workers/tiangong.py
  server/model_workers/xinghuo.py
  server/model_workers/zhipu.py
  server/utils.py
Labels: size:L

#2748 0.2.10(0.2.x Final dev release)
  README.md
  README_en.md
  configs/__init__.py
  configs/kb_config.py.example
  configs/model_config.py.example
  configs/server_config.py.example
  document_loaders/__init__.py
  document_loaders/mydocloader.py
  document_loaders/mypdfloader.py
  document_loaders/mypptloader.py
  embeddings/add_embedding_keywords.py
  img/qr_code_82.jpg
  img/qr_code_85.jpg
  init_database.py
  requirements.txt
  requirements_api.txt
  requirements_lite.txt
  requirements_webui.txt
  server/agent/custom_agent/ChatGLM3Agent.py
  server/agent/model_contain.py
  server/agent/tools/__init__.py
  server/agent/tools/arxiv.yaml
  server/agent/tools/calculate.yaml
  server/agent/tools/search_internet.yaml
  server/agent/tools/search_knowledgebase_complex.yaml
  server/agent/tools/search_youtube.yaml
  server/agent/tools/shell.yaml
  server/agent/tools/weather_check.py
  server/agent/tools/weather_check.yaml
  server/agent/tools/wolfram.yaml
  server/agent/tools_select.py
  server/callback_handler/conversation_callback_handler.py
  server/chat/agent_chat.py
  server/chat/search_engine_chat.py
  server/db/repository/knowledge_file_repository.py
  server/knowledge_base/kb_service/base.py
  server/knowledge_base/kb_service/es_kb_service.py
  server/knowledge_base/kb_service/faiss_kb_service.py
  server/knowledge_base/kb_service/milvus_kb_service.py
  server/knowledge_base/kb_service/pg_kb_service.py
  server/knowledge_base/kb_service/zilliz_kb_service.py
  server/knowledge_base/migrate.py
  server/knowledge_base/utils.py
  server/minx_chat_openai.py
  server/model_workers/__init__.py
  server/model_workers/gemini.py
  server/model_workers/minimax.py
  server/model_workers/qianfan.py
  server/model_workers/tiangong.py
  server/model_workers/xinghuo.py
  server/model_workers/zhipu.py
  server/static/swagger-ui-bundle.js
  server/utils.py
  startup.py
  tests/samples/ocr_test.docx
  tests/samples/ocr_test.pptx
  tests/test_migrate.py
  webui_pages/utils.py
Labels: size:XXL

#2750 配置文件修改
  configs/model_config.py.example
  requirements.txt
  requirements_api.txt
  server/chat/agent_chat.py
  server/model_workers/zhipu.py
Labels: size:M

#2751 恢复 删除知识库选项
  webui_pages/knowledge_base/knowledge_base.py
Labels: size:L

#2752 gemini API 修复
  configs/server_config.py.example
  server/knowledge_base/kb_api.py
  server/model_workers/gemini.py
  webui_pages/dialogue/dialogue.py
Labels: size:L

#2753 细节更新和补充
  README.md
  README_en.md
  configs/model_config.py.example
  configs/server_config.py.example
  document_loaders/mypdfloader.py
  img/qr_code_85.jpg
  img/qr_code_87.jpg
  requirements.txt
  requirements_api.txt
  requirements_lite.txt
  requirements_webui.txt
  server/embeddings_api.py
  server/knowledge_base/kb_cache/faiss_cache.py
  server/knowledge_base/kb_doc_api.py
  server/knowledge_base/kb_service/base.py
  server/knowledge_base/kb_service/milvus_kb_service.py
  server/knowledge_base/kb_service/pg_kb_service.py
  server/knowledge_base/kb_summary/base.py
  server/knowledge_base/kb_summary/summary_chunk.py
  server/knowledge_base/utils.py
  server/model_workers/azure.py
  server/model_workers/baichuan.py
  server/model_workers/base.py
  server/model_workers/fangzhou.py
  server/model_workers/gemini.py
  server/model_workers/minimax.py
  server/model_workers/qianfan.py
  server/model_workers/qwen.py
  server/model_workers/tiangong.py
  server/model_workers/xinghuo.py
  server/utils.py
  startup.py
  webui_pages/dialogue/dialogue.py
Labels: size:L

#2754 更新文档细节和readme细节
  README.md
  README_en.md
  configs/model_config.py.example
  configs/server_config.py.example
  document_loaders/mypdfloader.py
  img/qr_code_85.jpg
  img/qr_code_87.jpg
  requirements.txt
  requirements_api.txt
  requirements_lite.txt
  requirements_webui.txt
  server/embeddings_api.py
  server/knowledge_base/kb_api.py
  server/knowledge_base/kb_cache/faiss_cache.py
  server/knowledge_base/kb_doc_api.py
  server/knowledge_base/kb_service/base.py
  server/knowledge_base/kb_service/milvus_kb_service.py
  server/knowledge_base/kb_service/pg_kb_service.py
  server/knowledge_base/kb_summary/base.py
  server/knowledge_base/kb_summary/summary_chunk.py
  server/knowledge_base/utils.py
  server/model_workers/azure.py
  server/model_workers/baichuan.py
  server/model_workers/base.py
  server/model_workers/fangzhou.py
  server/model_workers/gemini.py
  server/model_workers/minimax.py
  server/model_workers/qianfan.py
  server/model_workers/qwen.py
  server/model_workers/tiangong.py
  server/model_workers/xinghuo.py
  server/utils.py
  startup.py
  webui_pages/dialogue/dialogue.py
  webui_pages/knowledge_base/knowledge_base.py
Labels: size:L

#2759 更新依赖错误
  requirements.txt
  requirements_api.txt
  requirements_lite.txt
Labels: size:S

#2782 Dev
  configs/server_config.py.example
  requirements.txt
  requirements_api.txt
  requirements_lite.txt
  webui_pages/dialogue/dialogue.py
  webui_pages/utils.py
Labels: size:S

#2787 Add README_ja.md
  README.md
  README_en.md
  README_ja.md
Labels: size:L

#2809 Update README.md
  README.md
Labels: size:XS

#2820 支持Chroma向量数据库
  configs/kb_config.py.example
  requirements.txt
  requirements_lite.txt
  server/knowledge_base/kb_service/base.py
  server/knowledge_base/kb_service/chromadb_kb_service.py
Labels: size:L

#2843 更新文件
  README.md
  README_en.md
  README_ja.md
  img/qr_code_86.jpg
  img/qr_code_87.jpg
  img/qr_code_88.jpg
  requirements.txt
  requirements_api.txt
  requirements_lite.txt
Labels: size:S

#2816 修复PDF旋转的BUG (Issues #2792)
  .gitignore
  README.md
  document_loaders/mypdfloader.py
  img/qr_code_86.jpg
  img/qr_code_87.jpg
  requirements.txt
  requirements_lite.txt
Labels: size:M

#2856 更新掉部分错误的依赖
  README.md
  README_en.md
  README_ja.md
  configs/kb_config.py.example
  requirements.txt
  requirements_api.txt
  requirements_lite.txt
  server/knowledge_base/kb_service/chromadb_kb_service.py
  server/knowledge_base/kb_service/milvus_kb_service.py
  server/static/swagger-ui-bundle.js
  startup.py
Labels: size:L

#2857 autodl代号错误修复
  README.md
  README_en.md
  README_ja.md
Labels: size:XS

#2858 修复部分问题
  .gitignore
  README.md
  README_en.md
  README_ja.md
  configs/kb_config.py.example
  document_loaders/mypdfloader.py
  requirements.txt
  requirements_api.txt
  requirements_lite.txt
  server/knowledge_base/kb_service/base.py
  server/knowledge_base/kb_service/chromadb_kb_service.py
  server/knowledge_base/kb_service/milvus_kb_service.py
  server/static/swagger-ui-bundle.js
  startup.py
Labels: size:L

#2868 修复milvus相关bug
  server/db/repository/knowledge_file_repository.py
  server/knowledge_base/kb_service/base.py
  server/knowledge_base/kb_service/milvus_kb_service.py
Labels: size:M

#2869 支持星火3.5模型
  configs/model_config.py.example
  server/model_workers/xinghuo.py
Labels: size:XS
