Repository chatchat-space/Langchain-Chatchat, pull requests merged in 2024-07, with the labels that each got.

#4367 修改api文档中手动输入工具参数的说明
  docs/contributing/api.md
Labels: size:XS

#4370 解决text2sql对GLM的兼容，即temperature不能设置为0
  libs/chatchat-server/chatchat/configs/_model_config.py
  libs/chatchat-server/chatchat/server/agent/tools_factory/text2sql.py
Labels: size:XS

#4351 fix:解决es数据库删除时只能删除50条数据的BUG
  libs/chatchat-server/chatchat/server/knowledge_base/kb_service/es_kb_service.py
Labels: size:S, lgtm

#4396 知识库接口对接完毕
  frontend/src/app/api/knowledge/list/route.ts
  frontend/src/app/api/knowledge/searchDocs/route.ts
  frontend/src/app/api/knowledge/updateDocs/route.ts
  frontend/src/app/knowledge/(desktop)/features/ModalCreateKnowledge.tsx
  frontend/src/app/knowledge/(desktop)/index.tsx
  frontend/src/app/knowledge/[id]/base/[fileId]/features/ModalSegment.tsx
  frontend/src/app/knowledge/[id]/base/[fileId]/page.tsx
  frontend/src/app/knowledge/[id]/base/features/ModalAddFile.tsx
  frontend/src/app/knowledge/[id]/base/page.tsx
  frontend/src/app/knowledge/[id]/layout.tsx
  frontend/src/app/knowledge/[id]/tabs/index.tsx
  frontend/src/app/knowledge/测试.txt
  frontend/src/config/server/provider.ts
  frontend/src/libs/agent-runtime/chatchat/index.ts
  frontend/src/services/_url.ts
  frontend/src/services/knowledge.ts
  frontend/src/store/knowledge/action.ts
  frontend/src/types/knowledge.ts
Labels: size:XL

#4399 feat:text2promql
  libs/chatchat-server/chatchat/configs/_model_config.py
  libs/chatchat-server/chatchat/server/agent/tools_factory/__init__.py
  libs/chatchat-server/chatchat/server/agent/tools_factory/text2promql.py
Labels: size:L

#4419 tool factory增加了维基百科搜索、高德地图天气查询、高德地图POI搜索
  libs/chatchat-server/chatchat/configs/_model_config.py
  libs/chatchat-server/chatchat/server/agent/tools_factory/__init__.py
  libs/chatchat-server/chatchat/server/agent/tools_factory/amap_poi_search.py
  libs/chatchat-server/chatchat/server/agent/tools_factory/amap_weather.py
  libs/chatchat-server/chatchat/server/agent/tools_factory/wikipedia_search.py
Labels: size:L

#4425 chatchat init 可以直接指定 Xinference API 地址、LLM 模型、Embedding 模型，一步完成知识库初始化
  README.md
  libs/chatchat-server/chatchat/cli.py
  libs/chatchat-server/chatchat/pydantic_settings_file.py
  libs/chatchat-server/chatchat/server/chat/chat.py
  libs/chatchat-server/chatchat/server/chat/file_chat.py
  libs/chatchat-server/chatchat/server/knowledge_base/kb_service/es_kb_service.py
  libs/chatchat-server/chatchat/server/knowledge_base/utils.py
  libs/chatchat-server/chatchat/settings.py
  libs/chatchat-server/chatchat/webui_pages/dialogue/dialogue.py
Labels: size:L

#4433 feat:support openai platform
  libs/chatchat-server/chatchat/settings.py
Labels: size:S, lgtm

#4434 Feat/dev test
  libs/chatchat-server/chatchat/server/agent/tools_factory/text2promql.py
  libs/chatchat-server/chatchat/settings.py
Labels: size:S

#4435 Feat/dev test
  libs/chatchat-server/chatchat/server/agent/tools_factory/text2promql.py
Labels: size:S

#4336 fix:解决天气、text2Sql Agent运行报错的BUG
  libs/chatchat-server/chatchat/webui_pages/dialogue/dialogue.py
Labels: size:S

#4331 修复某些提问导致rerank张量扩展大小不匹配的问题
  libs/chatchat-server/chatchat/server/reranker/reranker.py
Labels: size:L

#4451 添加单独的知识库问答 UI 页面
  docs/contributing/api.md
  libs/chatchat-server/chatchat/server/agent/tools_factory/search_internet.py
  libs/chatchat-server/chatchat/server/agent/tools_factory/tools_registry.py
  libs/chatchat-server/chatchat/server/api_server/chat_routes.py
  libs/chatchat-server/chatchat/server/api_server/kb_routes.py
  libs/chatchat-server/chatchat/server/chat/kb_chat.py
  libs/chatchat-server/chatchat/server/knowledge_base/kb_doc_api.py
  libs/chatchat-server/chatchat/server/knowledge_base/utils.py
  libs/chatchat-server/chatchat/server/utils.py
  libs/chatchat-server/chatchat/settings.py
  libs/chatchat-server/chatchat/startup.py
  libs/chatchat-server/chatchat/webui.py
  libs/chatchat-server/chatchat/webui_pages/dialogue/dialogue.py
  libs/chatchat-server/chatchat/webui_pages/kb_chat.py
  libs/chatchat-server/chatchat/webui_pages/utils.py
Labels: size:XL

#4468 弃用global_model_name，增加text2sql使用说明文档
  docs/install/README_text2sql.md
  libs/chatchat-server/README.md
  libs/chatchat-server/chatchat/server/agent/tools_factory/text2sql.py
  libs/chatchat-server/chatchat/server/api_server/chat_routes.py
  libs/chatchat-server/chatchat/settings.py
Labels: size:M

#4471 Add RAG page
  docs/contributing/api.md
  libs/chatchat-server/chatchat/server/agent/tools_factory/search_internet.py
  libs/chatchat-server/chatchat/server/agent/tools_factory/tools_registry.py
  libs/chatchat-server/chatchat/server/api_server/chat_routes.py
  libs/chatchat-server/chatchat/server/api_server/kb_routes.py
  libs/chatchat-server/chatchat/server/chat/kb_chat.py
  libs/chatchat-server/chatchat/server/knowledge_base/kb_doc_api.py
  libs/chatchat-server/chatchat/server/knowledge_base/utils.py
  libs/chatchat-server/chatchat/server/utils.py
  libs/chatchat-server/chatchat/settings.py
  libs/chatchat-server/chatchat/startup.py
  libs/chatchat-server/chatchat/webui.py
  libs/chatchat-server/chatchat/webui_pages/dialogue/dialogue.py
  libs/chatchat-server/chatchat/webui_pages/kb_chat.py
  libs/chatchat-server/chatchat/webui_pages/utils.py
Labels: size:XL

#4477 Dev
  .gitignore
  README.md
  README_en.md
  docs/contributing/agent.md
  libs/chatchat-server/chatchat/server/agent/agent_factory/agents_registry.py
  libs/chatchat-server/chatchat/settings.py
Labels: size:L

#4478 Strategy matrix ubuntu python
  .github/workflows/_integration_test.yml
  .github/workflows/_release.yml
  .github/workflows/_test.yml
  libs/chatchat-server/tests/integration_tests/test_sdk_import.py
Labels: size:L

#4480 updated workflow with the conditional steps for different operating systems
  .github/workflows/_integration_test.yml
  .github/workflows/_test.yml
  libs/chatchat-server/chatchat/configs/_core_config.py
Labels: size:M

#4484 文档完善
  docs/contributing/agent.md
  libs/chatchat-server/chatchat/server/agent/agent_instruct.md
Labels: size:L

#4491 fix: system message of webui not work (close #4408)
  libs/chatchat-server/chatchat/server/api_server/chat_routes.py
  libs/chatchat-server/chatchat/webui_pages/dialogue/dialogue.py
Labels: size:XS

#4498 remove vqa_processor & aqa_processor tools
  libs/chatchat-server/chatchat/server/agent/container.py
  libs/chatchat-server/chatchat/server/agent/tools_factory/__init__.py
  libs/chatchat-server/chatchat/server/agent/tools_factory/aqa_processor.py
  libs/chatchat-server/chatchat/server/agent/tools_factory/vqa_processor.py
  libs/chatchat-server/chatchat/settings.py
Labels: size:L

#4501 fix: KeyError of 'template'
  libs/chatchat-server/chatchat/server/api_server/chat_routes.py
  libs/chatchat-server/chatchat/server/api_server/server_routes.py
  libs/chatchat-server/chatchat/server/chat/chat.py
  libs/chatchat-server/chatchat/server/chat/completion.py
  libs/chatchat-server/chatchat/server/chat/file_chat.py
  libs/chatchat-server/chatchat/server/utils.py
  libs/chatchat-server/chatchat/settings.py
  libs/chatchat-server/tests/api/test_server_state_api.py
Labels: size:M

#4504 优化 searx 搜索引擎
  libs/chatchat-server/chatchat/server/agent/tools_factory/search_internet.py
  libs/chatchat-server/chatchat/server/utils.py
  libs/chatchat-server/chatchat/settings.py
Labels: size:S

#4507 修复init时，调用shutil.copytree，当src与dst一样时shutil报错的问题
  libs/chatchat-server/chatchat/cli.py
Labels: size:XS

#4510 一些性能优化
  libs/chatchat-server/chatchat/server/api_server/chat_routes.py
  libs/chatchat-server/chatchat/server/api_server/openai_routes.py
  libs/chatchat-server/chatchat/server/chat/chat.py
  libs/chatchat-server/chatchat/server/chat/completion.py
  libs/chatchat-server/chatchat/server/chat/file_chat.py
  libs/chatchat-server/chatchat/server/chat/kb_chat.py
  libs/chatchat-server/chatchat/server/file_rag/retrievers/base.py
  libs/chatchat-server/chatchat/server/file_rag/retrievers/ensemble.py
  libs/chatchat-server/chatchat/server/file_rag/retrievers/vectorstore.py
  libs/chatchat-server/chatchat/server/knowledge_base/kb_doc_api.py
  libs/chatchat-server/chatchat/server/knowledge_base/kb_summary_api.py
  libs/chatchat-server/chatchat/server/utils.py
  libs/chatchat-server/chatchat/webui_pages/dialogue/dialogue.py
Labels: size:XXL

#4511 Feat/docker update
  README.md
  docker/.dockerignore
  docker/Dockerfile
  docker/docker-compose.yaml
  libs/chatchat-server/pyproject.toml
Labels: size:M, lgtm

#4517 fix: duplicated logs in chatchat.log
  libs/chatchat-server/chatchat/cli.py
  libs/chatchat-server/chatchat/utils.py
Labels: size:XS

#4523 fix: nltk data path was not set correctlly
  libs/chatchat-server/chatchat/cli.py
  libs/chatchat-server/chatchat/server/utils.py
Labels: size:S

#4531 优化logs、错误信息的传递和前端显示
  libs/chatchat-server/chatchat/init_database.py
  libs/chatchat-server/chatchat/server/api_server/chat_routes.py
  libs/chatchat-server/chatchat/server/api_server/openai_routes.py
  libs/chatchat-server/chatchat/server/api_server/tool_routes.py
  libs/chatchat-server/chatchat/server/chat/chat.py
  libs/chatchat-server/chatchat/server/chat/kb_chat.py
  libs/chatchat-server/chatchat/server/knowledge_base/kb_cache/faiss_cache.py
  libs/chatchat-server/chatchat/server/knowledge_base/kb_doc_api.py
  libs/chatchat-server/chatchat/server/knowledge_base/kb_service/base.py
  libs/chatchat-server/chatchat/server/knowledge_base/kb_summary_api.py
  libs/chatchat-server/chatchat/server/knowledge_base/utils.py
  libs/chatchat-server/chatchat/server/localai_embeddings.py
  libs/chatchat-server/chatchat/server/utils.py
  libs/chatchat-server/chatchat/utils.py
  libs/chatchat-server/chatchat/webui_pages/dialogue/dialogue.py
  libs/chatchat-server/chatchat/webui_pages/kb_chat.py
Labels: size:L

#4540 优化 openai.chat.completions.create 参数构造方式，提高兼容性 （close #4533)
  libs/chatchat-server/chatchat/settings.py
  libs/chatchat-server/chatchat/webui_pages/dialogue/dialogue.py
Labels: size:M

#4547 新增URL内容阅读器：通过jina-ai/reader项目，将url内容处理为llm易于理解的文本形式
  libs/chatchat-server/chatchat/server/agent/tools_factory/__init__.py
  libs/chatchat-server/chatchat/server/agent/tools_factory/url_reader.py
  libs/chatchat-server/chatchat/settings.py
Labels: size:M

#4548 fix: langchain 版本升级后，DocumentWithVsId 出现 id 重复问题
  libs/chatchat-server/chatchat/server/knowledge_base/kb_doc_api.py
  libs/chatchat-server/chatchat/server/knowledge_base/kb_service/base.py
  libs/chatchat-server/chatchat/server/knowledge_base/kb_summary_api.py
Labels: size:XS

#4549 fix: 重建知识库时只处理了一个知识库
  libs/chatchat-server/chatchat/server/knowledge_base/migrate.py
Labels: size:XS

#4554 优化qwen模型下对tools的json修复成功率
  libs/chatchat-server/chatchat/server/agent/agent_factory/qwen_agent.py
Labels: size:S

#4560 修复PG向量库删除知识库文件时只删除当前知识库文件
  libs/chatchat-server/chatchat/server/knowledge_base/kb_service/pg_kb_service.py
Labels: size:S

#4564 fix: chat api error because openapi set max_tokens to 0 by default
  libs/chatchat-server/chatchat/server/api_server/chat_routes.py
  libs/chatchat-server/chatchat/server/api_server/kb_routes.py
  libs/chatchat-server/chatchat/server/api_server/openai_routes.py
  libs/chatchat-server/chatchat/server/chat/kb_chat.py
  libs/chatchat-server/chatchat/server/knowledge_base/kb_summary_api.py
Labels: size:S

#4536 Fix Milvus retriever NotImplementedError
  libs/chatchat-server/chatchat/server/file_rag/retrievers/__init__.py
  libs/chatchat-server/chatchat/server/file_rag/retrievers/milvus_vectorstore.py
  libs/chatchat-server/chatchat/server/file_rag/utils.py
  libs/chatchat-server/chatchat/server/knowledge_base/kb_service/milvus_kb_service.py
Labels: size:L

#4567 添加配置项，以便使用云服务器或反向代理时生成正确的公网 API 地址（如知识库文档下载链接）
  libs/chatchat-server/chatchat/cli.py
  libs/chatchat-server/chatchat/server/api_server/openai_routes.py
  libs/chatchat-server/chatchat/server/chat/kb_chat.py
  libs/chatchat-server/chatchat/server/knowledge_base/utils.py
  libs/chatchat-server/chatchat/server/utils.py
  libs/chatchat-server/chatchat/settings.py
  libs/chatchat-server/chatchat/webui_pages/dialogue/dialogue.py
  libs/chatchat-server/chatchat/webui_pages/kb_chat.py
Labels: size:M

#4541 Fix bug of ChromaDB Collection has no attribute 'as_retriever'
  libs/chatchat-server/chatchat/server/knowledge_base/kb_service/chromadb_kb_service.py
Labels: size:S

#4575 update docs
  README.md
  docker/docker-compose.yaml
  docs/install/README_docker.md
  libs/chatchat-server/README_en.md
Labels: size:S

#4581 真-修复：nltk_data 路径未正确设置导致 nltk download 错误， 以及 txt 等文档入库失败
  libs/chatchat-server/chatchat/cli.py
  libs/chatchat-server/chatchat/settings.py
Labels: size:XS

#4619 Feat/docker
  .github/workflows/docker-build.yaml
  README.md
  docker/.dockerignore
  docker/Dockerfile
  docker/Image Build ＆ YAML Setup.md
  docker/docker-compose.yaml
  docker/langchain_sample.yaml
Labels: size:L

#4629 fix: 参考文档和图片链接错误
  docs/contributing/README_dev.md
  libs/chatchat-server/chatchat/server/knowledge_base/utils.py
  libs/chatchat-server/chatchat/webui_pages/dialogue/dialogue.py
Labels: size:S

#4630 Feat/docker action
  .github/workflows/docker-build.yaml
  README.md
  docker/docker-compose.yaml
Labels: size:M

#4631 feat:action docker
  .github/workflows/docker-build.yaml
Labels: size:XS

#4632 feat:更改版本获取方式
  .github/workflows/docker-build.yaml
Labels: size:XS

#4616 fix: Milvus 数据库 top_k 未使用
  libs/chatchat-server/chatchat/server/file_rag/retrievers/milvus_vectorstore.py
Labels: size:S

#4637 Feat/docker action
  .github/workflows/docker-build.yaml
Labels: size:XS

#4638 Feat/docker action
  .github/workflows/docker-build.yaml
Labels: size:XS

#4651 Update README.md
  README.md
Labels: size:XS
