Repository chatchat-space/Langchain-Chatchat, pull requests merged in 2024-03, with the labels that each got.

#2892 Docker镜像制作与K8S YAML部署操作说明
  Dockerfile
  Image Build ＆ YAML Setup.md
  langchain_sample.yaml
Labels: size:L

#3155 修复使用Milvus数据库时上传知识库文件报错的问题
  server/knowledge_base/kb_doc_api.py
Labels: size:XS

#3184 windows下启动失败提示补充python-multipart包
  requirements.txt
Labels: size:XS

#3228 make qwen agent work with langchain>=0.1
  server/agent/agent_factory/agents_registry.py
  server/agent/agent_factory/qwen_agent.py
  server/callback_handler/agent_callback_handler.py
  tests/test_qwen_agent.py
Labels: size:M

#3247 feat:提交logo样式切换
  frontend/locales/zh-CN/common.json
  frontend/locales/zh-CN/welcome.json
  frontend/package.json
  frontend/public/images/Chatchat.png
  frontend/public/images/chathead.webp
  frontend/public/images/logo.png
  frontend/src/app/chat/(desktop)/features/SessionHeader.tsx
  frontend/src/app/chat/(mobile)/features/SessionHeader.tsx
  frontend/src/app/chat/features/ChatHeader/ShareButton/Preview.tsx
  frontend/src/app/market/(desktop)/features/Header.tsx
  frontend/src/app/market/(mobile)/features/Header.tsx
  frontend/src/app/settings/(mobile)/features/Header/Home.tsx
  frontend/src/app/welcome/(desktop)/layout.desktop.tsx
  frontend/src/app/welcome/(mobile)/features/Header.tsx
  frontend/src/app/welcome/features/Banner/Hero.tsx
  frontend/src/components/FullscreenLoading/index.tsx
  frontend/src/components/Logo/Divider.tsx
  frontend/src/components/Logo/LogoHighContrast.tsx
  frontend/src/components/Logo/LogoText.tsx
  frontend/src/components/Logo/demos/ExtraText.tsx
  frontend/src/components/Logo/demos/index.tsx
  frontend/src/components/Logo/index.md
  frontend/src/components/Logo/index.tsx
  frontend/src/components/Logo/style.ts
  frontend/src/locales/default/common.ts
  frontend/src/locales/default/welcome.ts
Labels: size:L

#3276 提高几十倍导入知识库的速度
  README.md
  img/qr_code_90.jpg
  img/qr_code_91.jpg
  img/qr_code_92.jpg
  img/qr_code_93.jpg
  img/qr_code_94.jpg
  img/qr_code_95.jpg
  img/qr_code_96.jpg
  img/qrcode_90_2.jpg
  server/knowledge_base/kb_doc_api.py
  server/knowledge_base/utils.py
  server/utils.py
Labels: size:M

#3304 xinference的代码
  server/khazic
  server/schema_validators/__init__.py
  server/schema_validators/common_validator.py
  server/schema_validators/model_credential_schema_validator.py
  server/schema_validators/provider_credential_schema_validator.py
  server/utils/__init__.py
  server/utils/_compat.py
  server/utils/encoders.py
  server/utils/helper.py
Labels: size:L

#3311 Dev model provider
  README.md
  README_CN.md
  __init__.py
  callbacks/__init__.py
  callbacks/base_callback.py
  callbacks/logging_callback.py
  schema_validators/__init__.py
  schema_validators/common_validator.py
  schema_validators/model_credential_schema_validator.py
  schema_validators/provider_credential_schema_validator.py
Labels: size:XL

#3324 fix markdown header split (#1825)
  server/knowledge_base/kb_service/base.py
  server/knowledge_base/utils.py
Labels: size:S

#3404 Dev fix csv loader
  document_loaders/FilteredCSVloader.py
Labels: size:M

#3407 修复使用pgvector时get_doc_by_ids方法报错的bug及知识库文件删除后向量仍然存在的bug
  server/knowledge_base/kb_service/base.py
  server/knowledge_base/kb_service/es_kb_service.py
  server/knowledge_base/kb_service/pg_kb_service.py
Labels: size:S

#3486 update to pydantic v2
  requirements.txt
  server/agent/agent_factory/glm3_agent.py
  server/agent/tools_factory/arxiv.py
  server/agent/tools_factory/audio_factory/aqa.py
  server/agent/tools_factory/search_internet.py
  server/agent/tools_factory/search_local_knowledgebase.py
  server/agent/tools_factory/search_youtube.py
  server/agent/tools_factory/shell.py
  server/agent/tools_factory/text2image.py
  server/agent/tools_factory/vision_factory/vqa.py
  server/agent/tools_factory/weather_check.py
  server/agent/tools_factory/wolfram.py
  server/api_server/api_schemas.py
  server/chat/utils.py
  server/pydantic_types.py
  server/pydantic_v1.py
  server/pydantic_v2.py
  server/utils.py
Labels: size:M

#3508 dev分支解决pydantic版本冲突问题，增加ollama配置，支持ollama会话和向量接口
  configs/model_config.py.example
  server/api_server/api_schemas.py
  server/api_server/kb_routes.py
  server/api_server/openai_routes.py
  server/chat/utils.py
  server/knowledge_base/kb_doc_api.py
  server/utils.py
Labels: size:M

#3528 模型默认参数从配置文件加载
  model-providers/chatchat_model_providers/__main__.py
  model-providers/chatchat_model_providers/core/entities/provider_configuration.py
  model-providers/chatchat_model_providers/core/entities/provider_entities.py
  model-providers/chatchat_model_providers/core/model_manager.py
  model-providers/chatchat_model_providers/core/provider_manager.py
  model-providers/chatchat_model_providers/errors/error.py
Labels: size:XXL

#3553 重写 tool 部分: 简化 tool 定义方式；支持热加载
  chatchat-server/chatchat/configs/basic_config.py.example
  chatchat-server/chatchat/configs/kb_config.py.example
  chatchat-server/chatchat/configs/model_config.py.example
  chatchat-server/chatchat/configs/prompt_config.py.example
  chatchat-server/chatchat/configs/server_config.py.example
  chatchat-server/chatchat/server/agent/container.py
  chatchat-server/chatchat/server/agent/tools_factory/__init__.py
  chatchat-server/chatchat/server/agent/tools_factory/aqa_processor.py
  chatchat-server/chatchat/server/agent/tools_factory/arxiv.py
  chatchat-server/chatchat/server/agent/tools_factory/audio_factory/__init__.py
  chatchat-server/chatchat/server/agent/tools_factory/calculate.py
  chatchat-server/chatchat/server/agent/tools_factory/search_internet.py
  chatchat-server/chatchat/server/agent/tools_factory/search_local_knowledgebase.py
  chatchat-server/chatchat/server/agent/tools_factory/search_youtube.py
  chatchat-server/chatchat/server/agent/tools_factory/shell.py
  chatchat-server/chatchat/server/agent/tools_factory/text2image.py
  chatchat-server/chatchat/server/agent/tools_factory/tools_registry.py
  chatchat-server/chatchat/server/agent/tools_factory/vision_factory/__init__.py
  chatchat-server/chatchat/server/agent/tools_factory/vqa_processor.py
  chatchat-server/chatchat/server/agent/tools_factory/weather_check.py
  chatchat-server/chatchat/server/agent/tools_factory/wolfram.py
  chatchat-server/chatchat/server/api_server/tool_routes.py
  chatchat-server/chatchat/server/chat/chat.py
  chatchat-server/chatchat/server/utils.py
  chatchat-server/chatchat/webui_pages/dialogue/dialogue.py
Labels: size:XL

#3570 优化工具定义；添加 openai 兼容的统一 chat 接口
  chatchat-server/chatchat/server/agent/agent_factory/qwen_agent.py
  chatchat-server/chatchat/server/agent/tools_factory/aqa_processor.py
  chatchat-server/chatchat/server/agent/tools_factory/arxiv.py
  chatchat-server/chatchat/server/agent/tools_factory/calculate.py
  chatchat-server/chatchat/server/agent/tools_factory/search_internet.py
  chatchat-server/chatchat/server/agent/tools_factory/search_local_knowledgebase.py
  chatchat-server/chatchat/server/agent/tools_factory/search_youtube.py
  chatchat-server/chatchat/server/agent/tools_factory/shell.py
  chatchat-server/chatchat/server/agent/tools_factory/text2image.py
  chatchat-server/chatchat/server/agent/tools_factory/tools_registry.py
  chatchat-server/chatchat/server/agent/tools_factory/vqa_processor.py
  chatchat-server/chatchat/server/agent/tools_factory/weather_check.py
  chatchat-server/chatchat/server/agent/tools_factory/wolfram.py
  chatchat-server/chatchat/server/api_server/api_schemas.py
  chatchat-server/chatchat/server/api_server/chat_routes.py
  chatchat-server/chatchat/server/api_server/openai_routes.py
  chatchat-server/chatchat/server/api_server/tool_routes.py
  chatchat-server/chatchat/server/callback_handler/agent_callback_handler.py
  chatchat-server/chatchat/server/chat/chat.py
  chatchat-server/chatchat/server/knowledge_base/kb_service/es_kb_service.py
  chatchat-server/chatchat/server/knowledge_base/kb_service/faiss_kb_service.py
  chatchat-server/chatchat/webui_pages/dialogue/dialogue.py
  chatchat-server/chatchat/webui_pages/utils.py
Labels: size:XL

#3571 修复：search_local_knowledge_base 工具返回值错误；/tools 路由错误；webui 中“正在思考”一直显示
  chatchat-server/chatchat/server/agent/tools_factory/search_local_knowledgebase.py
  chatchat-server/chatchat/server/api_server/chat_routes.py
  chatchat-server/chatchat/server/api_server/tool_routes.py
  chatchat-server/chatchat/webui_pages/dialogue/dialogue.py
  chatchat-server/chatchat/webui_pages/utils.py
Labels: size:S
