Repository chatchat-space/Langchain-Chatchat, pull requests merged in 2024-06, with the labels that each got.

#4118 feat:README
  libs/chatchat-server/README.md
Labels: size:S

#4119 修改知识库列表接口、run_in_process_pool兼容性问题、poetry配置文件修复
  libs/chatchat-server/chatchat/server/agent/tools_factory/search_local_knowledgebase.py
  libs/chatchat-server/chatchat/server/db/models/knowledge_base_model.py
  libs/chatchat-server/chatchat/server/db/repository/knowledge_base_repository.py
  libs/chatchat-server/chatchat/server/knowledge_base/kb_service/base.py
  libs/chatchat-server/chatchat/server/knowledge_base/utils.py
  libs/chatchat-server/chatchat/server/utils.py
  libs/chatchat-server/pyproject.toml
Labels: size:L

#4117 知识库：列表、新增、删除接口对接
  frontend/.env.example
  frontend/next.config.mjs
  frontend/src/app/api/knowledge/add/route.ts
  frontend/src/app/api/knowledge/del/route.ts
  frontend/src/app/api/knowledge/list/route.ts
  frontend/src/app/api/knowledge/接口存在问题.txt
  frontend/src/app/knowledge/(desktop)/features/KnowledgeCard.tsx
  frontend/src/app/knowledge/(desktop)/features/KnowledgeList.tsx
  frontend/src/app/knowledge/(desktop)/features/ModalCreateKnowledge.tsx
  frontend/src/app/knowledge/(desktop)/index.tsx
  frontend/src/config/server/provider.ts
  frontend/src/services/_url.ts
  frontend/src/services/knowledge.ts
  frontend/src/store/knowledge/action.ts
  frontend/src/store/knowledge/index.ts
  frontend/src/store/knowledge/store.ts
  frontend/src/types/knowledge.ts
Labels: size:L

#4122 Dev init database providers关闭守护进程
  libs/chatchat-server/chatchat/init_database.py
  libs/chatchat-server/chatchat/startup.py
Labels: size:L

#4121 动态更新Prompt中的知识库描述信息，使大模型更容易判断使用哪个知识库。
  libs/chatchat-server/chatchat/server/utils.py
Labels: size:S

#4123 fix: 补充 xinference 配置信息
  libs/chatchat-server/chatchat/configs/model_providers.yaml
Labels: size:XS

#4126 知识库工具的下拉列表改为动态获取，不必重启服务。
  libs/chatchat-server/chatchat/server/utils.py
  libs/chatchat-server/chatchat/webui_pages/dialogue/dialogue.py
Labels: size:XS

#4130 知识库更改：接口对接、部分UI调整
  frontend/src/app/api/knowledge/delVectorDocs/route.ts
  frontend/src/app/api/knowledge/deleteDocs/route.ts
  frontend/src/app/api/knowledge/downloadDocs/route.ts
  frontend/src/app/api/knowledge/listFiles/route.ts
  frontend/src/app/api/knowledge/reAddVectorDB/route.ts
  frontend/src/app/api/knowledge/rebuildVectorDB/route.ts
  frontend/src/app/api/knowledge/update/route.ts
  frontend/src/app/api/knowledge/uploadDocs/route.ts
  frontend/src/app/api/knowledge/接口存在问题.txt
  frontend/src/app/knowledge/(desktop)/features/KnowledgeCard.tsx
  frontend/src/app/knowledge/(desktop)/features/KnowledgeList.tsx
  frontend/src/app/knowledge/(desktop)/features/ModalCreateKnowledge.tsx
  frontend/src/app/knowledge/(desktop)/index.tsx
  frontend/src/app/knowledge/[id]/base/features/ModalAddFile.tsx
  frontend/src/app/knowledge/[id]/base/page.tsx
  frontend/src/app/knowledge/[id]/config/page.tsx
  frontend/src/app/knowledge/[id]/layout.tsx
  frontend/src/services/_url.ts
  frontend/src/services/knowledge.ts
  frontend/src/store/knowledge/action.ts
  frontend/src/types/knowledge.ts
Labels: size:XL

#4153 优化知识库相关功能
  libs/chatchat-server/README.md
  libs/chatchat-server/chatchat/configs/_model_config.py
  libs/chatchat-server/chatchat/configs/model_providers.yaml
  libs/chatchat-server/chatchat/init_database.py
  libs/chatchat-server/chatchat/server/knowledge_base/kb_api.py
  libs/chatchat-server/chatchat/server/knowledge_base/kb_cache/base.py
  libs/chatchat-server/chatchat/server/knowledge_base/kb_cache/faiss_cache.py
  libs/chatchat-server/chatchat/server/knowledge_base/kb_doc_api.py
  libs/chatchat-server/chatchat/server/knowledge_base/kb_service/base.py
  libs/chatchat-server/chatchat/server/knowledge_base/kb_summary_api.py
  libs/chatchat-server/chatchat/server/knowledge_base/migrate.py
  libs/chatchat-server/chatchat/server/utils.py
  libs/chatchat-server/pyproject.toml
  tools/model_loaders/xinference_manager.py
Labels: size:L

#3966 修复glm-4 无法流式输出的bug
  server/model_workers/zhipu.py
Labels: size:M

#4154 增加text2sql工具，支持特定表、智能判定表，支持对表名进行额外说明
  libs/chatchat-server/chatchat/configs/_model_config.py
  libs/chatchat-server/chatchat/server/agent/tools_factory/__init__.py
  libs/chatchat-server/chatchat/server/agent/tools_factory/text2sql.py
  libs/chatchat-server/chatchat/server/api_server/chat_routes.py
  libs/chatchat-server/pyproject.toml
Labels: size:M

#4155 支持SQLAlchemy大部分数据库、新增read-only模式，提高安全性、增加text2sql使用建议
  libs/chatchat-server/chatchat/configs/_model_config.py
  libs/chatchat-server/chatchat/server/agent/tools_factory/text2sql.py
Labels: size:M

#4156 用户工作空间操作
  libs/chatchat-server/chatchat/config_work_space.py
  libs/chatchat-server/chatchat/configs/__init__.py
  libs/chatchat-server/chatchat/configs/_basic_config.py
  libs/chatchat-server/pyproject.toml
  libs/chatchat-server/tests/conftest.py
  libs/chatchat-server/tests/unit_tests/config/test_config.py
Labels: size:XL

#4157 Dev
  libs/chatchat-server/poetry.toml
  libs/chatchat-server/pyproject.toml
  libs/model-providers/poetry.toml
  poetry.toml
Labels: size:S

#4164 使用click增加配置中心子命令
  libs/chatchat-server/chatchat/config_work_space.py
  libs/chatchat-server/chatchat/configs/__init__.py
  libs/chatchat-server/chatchat/configs/_basic_config.py
  libs/chatchat-server/chatchat/configs/_core_config.py
  libs/chatchat-server/chatchat/configs/_model_config.py
  libs/chatchat-server/pyproject.toml
  libs/chatchat-server/tests/unit_tests/config/test_config.py
Labels: size:XXL

#4166 配置中心服务信息 子命令入口
  libs/chatchat-server/chatchat/config_work_space.py
  libs/chatchat-server/chatchat/configs/__init__.py
  libs/chatchat-server/chatchat/configs/_server_config.py
  libs/chatchat-server/tests/unit_tests/config/test_config.py
Labels: size:L

#4170 配置中心知识库信息 子命令入口
  libs/chatchat-server/chatchat/config_work_space.py
  libs/chatchat-server/chatchat/configs/__init__.py
  libs/chatchat-server/chatchat/configs/_kb_config.py
  libs/chatchat-server/tests/unit_tests/config/test_config.py
Labels: size:XL

#4179 update streamlit-aggrid; fix knowledge file status error
  libs/chatchat-server/chatchat/server/knowledge_base/kb_cache/faiss_cache.py
  libs/chatchat-server/chatchat/webui_pages/knowledge_base/knowledge_base.py
  libs/chatchat-server/pyproject.toml
Labels: size:S

#3206 faiss加载时，输入索引方式与实际初始化索引不符合
  libs/chatchat-server/chatchat/server/knowledge_base/kb_cache/faiss_cache.py
Labels: size:XS

#3477 Fix EventSourceResponse chunk splitting causes json loads to fail
  webui_pages/utils.py
Labels: size:M

#3821 修复reranker模型初始化bug
  server/reranker/reranker.py
Labels: size:XS

#3926 Add relyt vector store
  configs/kb_config.py.example
  requirements.txt
  server/knowledge_base/kb_service/base.py
  server/knowledge_base/kb_service/relyt_kb_service.py
  tests/kb_vector_db/test_relyt_db.py
Labels: size:L

#4135 fix: Enable pagination in the vector database to prevent the page
  webui_pages/knowledge_base/knowledge_base.py
Labels: size:XS

#3229 Enable langfuse for file_chat, knowledge_base_chat, search_engine_chat, and agent_chat
  server/chat/agent_chat.py
  server/chat/chat.py
  server/chat/file_chat.py
  server/chat/knowledge_base_chat.py
  server/chat/search_engine_chat.py
Labels: size:M

#4194 fix/fixOpenAIEmbeddingError
  libs/chatchat-server/README_dev.md
  libs/chatchat-server/chatchat/configs/model_providers.yaml
  libs/chatchat-server/chatchat/server/utils.py
  libs/model-providers/model_providers/bootstrap_web/openai_bootstrap_web.py
Labels: size:S

#4199 feat:quick start
  README.md
  libs/model-providers/model_providers.yaml
Labels: size:L

#4206 修复：知识库问答上下文未正确传递；更新 chatbox 依赖，清空会话时保留参数配置
  libs/chatchat-server/chatchat/configs/_prompt_config.py
  libs/chatchat-server/chatchat/server/agent/tools_factory/search_local_knowledgebase.py
  libs/chatchat-server/chatchat/server/api_server/chat_routes.py
  libs/chatchat-server/chatchat/server/chat/chat.py
  libs/chatchat-server/chatchat/server/chat/completion.py
  libs/chatchat-server/chatchat/webui_pages/dialogue/dialogue.py
  libs/chatchat-server/pyproject.toml
Labels: size:M

#4235 Readme
  .github/workflows/docker-build.yaml
  .gitignore
  README.md
  README_en.md
  README_ja.md
  docs/contributing/README.md
  docs/contributing/README_dev.md
  docs/install/README_xinference_en.md
  libs/chatchat-server/README.md
  libs/chatchat-server/README_en.md
  libs/chatchat-server/chatchat/server/chat/chat.py
  libs/model-providers/README.md
  libs/model-providers/README_en.md
  libs/model-providers/model_providers/core/model_runtime/README.md
  libs/model-providers/model_providers/core/model_runtime/README_CN.md
  libs/model-providers/model_providers/core/model_runtime/README_en.md
Labels: size:XXL

#4237 项目引用声明更新
  ADDITIONAL_LICENSE
  LICENSE
  README.md
  README_en.md
  libs/model-providers/README.md
  libs/model-providers/README_en.md
Labels: size:M

#4238 协议声明更新
  ADDITIONAL_LICENSE
  LICENSE
  README.md
  README_en.md
  libs/model-providers/README.md
  libs/model-providers/README_en.md
Labels: size:M

#4239 项目协议更新说明
  ADDITIONAL_LICENSE
  LICENSE
  README.md
  README_en.md
  libs/model-providers/README.md
  libs/model-providers/README_en.md
Labels: size:M

#4260 CICD github action build publish pypi、Release Tag
  .github/workflows/_release.yml
  .github/workflows/_test_release.yml
  libs/chatchat-server/Makefile
  libs/chatchat-server/chatchat/server/utils.py
  libs/chatchat-server/chatchat/startup.py
  libs/chatchat-server/langchain_chatchat/__init__.py
  libs/chatchat-server/pyproject.toml
  libs/chatchat-server/scripts/check_imports.py
  libs/chatchat-server/scripts/check_pydantic.sh
  libs/chatchat-server/scripts/lint_imports.sh
  libs/chatchat-server/tests/conftest.py
  libs/chatchat-server/tests/integration_tests/keep
  libs/chatchat-server/tests/integration_tests/unit_server/test_init_server.py
  libs/chatchat-server/tests/unit_server/test_init_server.py
  libs/chatchat-server/tests/unit_tests/config/test_config.py
  libs/chatchat-server/tests/unit_tests/test_sdk_import.py
  libs/model-providers/pyproject.toml
Labels: size:XL

#4263 Update README.md
  README.md
Labels: size:XS

#4274 feat:readme for docker
  docker/docker-compose.yaml
  docs/install/README_docker.md
Labels: size:L

#4281 Feat/docker doc
  docker/docker-compose.yaml
  docs/install/README_docker.md
Labels: size:S

#4283 update image to chatimage/chatchat:0.3.0-0623
  docker/Dockerfile
  docker/docker-compose.yaml
Labels: size:XS

#4285 feat:update image to chatimage/chatchat:0.3.0-0623-3
  .github/workflows/docker-build.yaml
  README.md
  docker/Dockerfile
  docker/docker-compose.yaml
  docs/install/README_docker.md
Labels: size:L

#4310 feat:update docker image to 0.3.0-2024-0624
  README.md
  docker/docker-compose.yaml
Labels: size:XS

#4330 在 readme 中增加对 windows 下创建知识库卡住的说明与解决办法
  .gitignore
  README.md
  README_en.md
Labels: size:M

#4341 添加 Agent & Chat API 接口调用的说明，修正知识库检索bug
  docs/contributing/api.md
  libs/chatchat-server/chatchat/configs/_kb_config.py
  libs/chatchat-server/chatchat/configs/_model_config.py
  libs/chatchat-server/chatchat/server/agent/tools_factory/search_local_knowledgebase.py
  libs/chatchat-server/chatchat/server/api_server/chat_routes.py
  libs/chatchat-server/chatchat/server/utils.py
  libs/chatchat-server/chatchat/webui_pages/dialogue/dialogue.py
  libs/chatchat-server/tests/api/test_stream_chat_api.py
Labels: size:L

#4344 统一搜索引擎与本地知识库返回格式，修改 WEBUI 渲染上下文方式
  libs/chatchat-server/chatchat/server/agent/tools_factory/search_internet.py
  libs/chatchat-server/chatchat/server/agent/tools_factory/search_local_knowledgebase.py
  libs/chatchat-server/chatchat/server/agent/tools_factory/text2sql.py
  libs/chatchat-server/chatchat/server/agent/tools_factory/tools_registry.py
  libs/chatchat-server/chatchat/webui_pages/dialogue/dialogue.py
Labels: size:L

#4349 修复文生图工具
  libs/chatchat-server/chatchat/configs/_model_config.py
  libs/chatchat-server/chatchat/server/agent/tools_factory/text2image.py
  libs/chatchat-server/chatchat/server/api_server/chat_routes.py
  libs/chatchat-server/chatchat/webui_pages/dialogue/dialogue.py
Labels: size:M

#4319 fix: fix the problem when Milvus is used as knowledge base
  libs/chatchat-server/chatchat/configs/_kb_config.py
  libs/chatchat-server/chatchat/server/knowledge_base/kb_service/milvus_kb_service.py
Labels: size:XS, lgtm

#4352 user can quit by Ctrl+C when init_data.py(chatchat-kb)
  libs/chatchat-server/chatchat/init_database.py
Labels: size:M

#4355 Fix/max_tokens
  libs/chatchat-server/chatchat/configs/_model_config.py
  libs/chatchat-server/chatchat/server/api_server/chat_routes.py
  libs/chatchat-server/chatchat/server/chat/chat.py
  libs/chatchat-server/chatchat/server/utils.py
  libs/chatchat-server/chatchat/webui_pages/dialogue/dialogue.py
Labels: size:M
