Repository chatchat-space/Langchain-Chatchat, pull requests merged in 2024-09, with the labels that each got.

#4907 Fixed [BUG] 无法加载EPUB和MSG文件到知识库 #4895
  libs/chatchat-server/chatchat/server/knowledge_base/utils.py
Labels: size:XS

#4921 feat:针对 reflexion agent 的 prompt 进行了, 优化了工作流效果和各 node 返回的 struct 的稳定性.
  libs/chatchat-server/chatchat/server/agent/graphs_factory/reflexion.py
  libs/chatchat-server/chatchat/server/chat/graph_chat.py
Labels: size:L

#4923 fix:修复了 plan_and_execute 错误.
  libs/chatchat-server/chatchat/server/agent/graphs_factory/plan_and_execute.py
  libs/chatchat-server/chatchat/webui_pages/dialogue/utils.py
Labels: size:XS

#4924 针对" URL 内容阅读"工具进行优化
  libs/chatchat-server/chatchat/server/agent/tools_factory/url_reader.py
  libs/chatchat-server/chatchat/settings.py
Labels: size:M

#4963 feat: Support for connecting ES using custom protocol
  libs/chatchat-server/chatchat/server/knowledge_base/kb_service/es_kb_service.py
  libs/chatchat-server/chatchat/settings.py
Labels: size:XS

#4971 support streamlit-markdown
  libs/chatchat-server/chatchat/server/api_server/server_app.py
  libs/chatchat-server/chatchat/settings.py
  libs/chatchat-server/chatchat/webui_pages/dialogue/dialogue.py
  libs/chatchat-server/chatchat/webui_pages/kb_chat.py
  libs/chatchat-server/pyproject.toml
Labels: size:S

#4976 add sqlite as stores supporting vector & bm25 search
  libs/chatchat-server/chatchat/server/file_rag/retrievers/__init__.py
  libs/chatchat-server/chatchat/server/knowledge_base/kb_service/base.py
  libs/chatchat-server/chatchat/server/knowledge_base/kb_service/sqlite_kb_service.py
  libs/chatchat-server/chatchat/settings.py
  libs/chatchat-server/pyproject.toml
Labels: size:L

#4985 fix: chroma error when clear_vs
  libs/chatchat-server/chatchat/server/knowledge_base/kb_service/chromadb_kb_service.py
Labels: size:XS
