Repository chatchat-space/Langchain-Chatchat, pull requests merged in 2024-08, with the labels that each got.

#4682 use Settings.kb_settings.DEFAULT_VS_TYPE in create_kb api
  libs/chatchat-server/chatchat/server/knowledge_base/kb_api.py
Labels: size:XS

#4649 fix:如果模型输出不是str，会导致ret=OpenAIChatOutput报错
  libs/chatchat-server/chatchat/server/chat/chat.py
Labels: size:XS

#4700 fix
  README.md
Labels: size:XS

#4717 Feature/agentgraph
  .github/workflows/docker-build.yaml
  README.md
  docker/docker-compose.yaml
  docs/contributing/api.md
  docs/img/qr_code_113_2.jpg
  docs/img/qr_code_114.jpg
  libs/chatchat-server/chatchat/server/agent/graphs_factory/__init__.py
  libs/chatchat-server/chatchat/server/agent/graphs_factory/base_graph.py
  libs/chatchat-server/chatchat/server/agent/graphs_factory/graphs_registry.py
  libs/chatchat-server/chatchat/server/agent/tools_factory/text2promql.py
  libs/chatchat-server/chatchat/server/api_server/chat_routes.py
  libs/chatchat-server/chatchat/server/api_server/graph_routes.py
  libs/chatchat-server/chatchat/server/api_server/server_app.py
  libs/chatchat-server/chatchat/server/api_server/tool_routes.py
  libs/chatchat-server/chatchat/server/chat/chat.py
  libs/chatchat-server/chatchat/server/chat/graph_chat.py
  libs/chatchat-server/chatchat/server/file_rag/retrievers/milvus_vectorstore.py
  libs/chatchat-server/chatchat/server/knowledge_base/kb_api.py
  libs/chatchat-server/chatchat/server/utils.py
  libs/chatchat-server/chatchat/settings.py
  libs/chatchat-server/chatchat/startup.py
  libs/chatchat-server/chatchat/webui.py
  libs/chatchat-server/chatchat/webui_pages/dialogue/dialogue.py
  libs/chatchat-server/chatchat/webui_pages/utils.py
  libs/chatchat-server/pyproject.toml
Labels: size:XL

#4821 Feature/agentgraph
  libs/chatchat-server/pyproject.toml
Labels: size:S

#4824 langgraph流程编排节点注册与langgraph动态编排：
  libs/chatchat-server/chatchat/server/api_server/api_schemas.py
  libs/chatchat-server/chatchat/server/api_server/flow_routes.py
  libs/chatchat-server/chatchat/server/api_server/server_app.py
  libs/chatchat-server/chatchat/server/langgraph/node_factory/__init__.py
  libs/chatchat-server/chatchat/server/langgraph/node_factory/build_flow.py
  libs/chatchat-server/chatchat/server/langgraph/node_factory/node1.py
  libs/chatchat-server/chatchat/server/langgraph/node_factory/node2.py
  libs/chatchat-server/chatchat/server/langgraph/node_factory/node3.py
  libs/chatchat-server/chatchat/server/langgraph/node_factory/node4.py
  libs/chatchat-server/chatchat/server/langgraph/node_factory/nodes_registry.py
Labels: size:L

#4833 feat: integrate PlatformToolsRunnable.ChatPlatformAI with structured chat agent and async invocation
  cli_demo.py
  libs/chatchat-server/chatchat/server/agent/agent_factory/__init__.py
  libs/chatchat-server/chatchat/server/agent/agent_factory/agents_registry.py
  libs/chatchat-server/chatchat/server/agent/agent_factory/glm3_agent.py
  libs/chatchat-server/chatchat/server/agent/agent_factory/qwen_agent.py
  libs/chatchat-server/chatchat/server/agent/tools_factory/tools_registry.py
  libs/chatchat-server/chatchat/server/chat/chat.py
  libs/chatchat-server/chatchat/server/utils.py
  libs/chatchat-server/chatchat/settings.py
  libs/chatchat-server/langchain_chatchat/__init__.py
  libs/chatchat-server/langchain_chatchat/agent_toolkits/__init__.py
  libs/chatchat-server/langchain_chatchat/agent_toolkits/all_tools/__init__.py
  libs/chatchat-server/langchain_chatchat/agent_toolkits/all_tools/code_interpreter_tool.py
  libs/chatchat-server/langchain_chatchat/agent_toolkits/all_tools/drawing_tool.py
  libs/chatchat-server/langchain_chatchat/agent_toolkits/all_tools/registry.py
  libs/chatchat-server/langchain_chatchat/agent_toolkits/all_tools/struct_type.py
  libs/chatchat-server/langchain_chatchat/agent_toolkits/all_tools/tool.py
  libs/chatchat-server/langchain_chatchat/agent_toolkits/all_tools/web_browser_tool.py
  libs/chatchat-server/langchain_chatchat/agents/__init__.py
  libs/chatchat-server/langchain_chatchat/agents/agents_registry/__init__.py
  libs/chatchat-server/langchain_chatchat/agents/agents_registry/agents_registry.py
  libs/chatchat-server/langchain_chatchat/agents/all_tools_agent.py
  libs/chatchat-server/langchain_chatchat/agents/format_scratchpad/all_tools.py
  libs/chatchat-server/langchain_chatchat/agents/output_parsers/__init__.py
  libs/chatchat-server/langchain_chatchat/agents/output_parsers/glm3_output_parsers.py
  libs/chatchat-server/langchain_chatchat/agents/output_parsers/platform_tools.py
  libs/chatchat-server/langchain_chatchat/agents/output_parsers/qwen_output_parsers.py
  libs/chatchat-server/langchain_chatchat/agents/output_parsers/structured_chat_output_parsers.py
  libs/chatchat-server/langchain_chatchat/agents/output_parsers/tools_output/__init__.py
  libs/chatchat-server/langchain_chatchat/agents/output_parsers/tools_output/_utils.py
  libs/chatchat-server/langchain_chatchat/agents/output_parsers/tools_output/base.py
  libs/chatchat-server/langchain_chatchat/agents/output_parsers/tools_output/code_interpreter.py
  libs/chatchat-server/langchain_chatchat/agents/output_parsers/tools_output/drawing_tool.py
  libs/chatchat-server/langchain_chatchat/agents/output_parsers/tools_output/function.py
  libs/chatchat-server/langchain_chatchat/agents/output_parsers/tools_output/tools.py
  libs/chatchat-server/langchain_chatchat/agents/output_parsers/tools_output/web_browser.py
  libs/chatchat-server/langchain_chatchat/agents/platform_tools/__init__.py
  libs/chatchat-server/langchain_chatchat/agents/platform_tools/base.py
  libs/chatchat-server/langchain_chatchat/agents/platform_tools/schema.py
  libs/chatchat-server/langchain_chatchat/agents/react/create_prompt_template.py
  libs/chatchat-server/langchain_chatchat/agents/structured_chat/__init__.py
  libs/chatchat-server/langchain_chatchat/agents/structured_chat/glm3_agent.py
  libs/chatchat-server/langchain_chatchat/agents/structured_chat/platform_tools_bind.py
  libs/chatchat-server/langchain_chatchat/agents/structured_chat/qwen_agent.py
  libs/chatchat-server/langchain_chatchat/agents/structured_chat/structured_chat_agent.py
  libs/chatchat-server/langchain_chatchat/callbacks/__init__.py
  libs/chatchat-server/langchain_chatchat/callbacks/agent_callback_handler.py
  libs/chatchat-server/langchain_chatchat/chat_models/__init__.py
  libs/chatchat-server/langchain_chatchat/chat_models/base.py
  libs/chatchat-server/langchain_chatchat/chat_models/platform_tools_message.py
  libs/chatchat-server/langchain_chatchat/embeddings/__init__.py
  libs/chatchat-server/langchain_chatchat/utils/__init__.py
  libs/chatchat-server/langchain_chatchat/utils/history.py
  libs/chatchat-server/langchain_chatchat/utils/try_parse_json_object.py
  libs/chatchat-server/pyproject.toml
  libs/chatchat-server/tests/integration_tests/platform_tools/test_platform_tools.py
Labels: size:XXL

#4832 fix nltk_data path problem
  libs/chatchat-server/chatchat/settings.py
  libs/chatchat-server/chatchat/utils.py
Labels: size:XS

#4835 Feature/graph chat forntend optimization
  libs/chatchat-server/chatchat/server/agent/graphs_factory/base_graph.py
  libs/chatchat-server/chatchat/server/agent/graphs_factory/graphs_registry.py
  libs/chatchat-server/chatchat/server/api_server/chat_routes.py
  libs/chatchat-server/chatchat/server/chat/graph_chat.py
  libs/chatchat-server/chatchat/webui_pages/dialogue/dialogue.py
Labels: size:L

#4852 fix:arxiv() got an unexpected keyword argument 'title'
  libs/chatchat-server/chatchat/server/agent/tools_factory/arxiv.py
  libs/chatchat-server/pyproject.toml
Labels: size:XS

#4853 feat: add tavily search
  libs/chatchat-server/chatchat/server/agent/tools_factory/search_internet.py
  libs/chatchat-server/chatchat/settings.py
Labels: size:S

#4861 Issue title contains advertisement keywords.
  .github/workflows/label_ad_issue.yml
Labels: size:M

#4864 label_ad_issue.yml
  .github/workflows/label_ad_issue.yml
Labels: size:XS

#4866 environment: Scheduled GITHUB_OWNER publish
  .github/workflows/label_ad_issue.yml
Labels: size:XS

#4705 fix: The top_k value of the retriever cannot be specified.
  libs/chatchat-server/chatchat/server/file_rag/retrievers/ensemble.py
  libs/chatchat-server/chatchat/server/file_rag/retrievers/vectorstore.py
Labels: size:XS

#4887 feat:add graph_chat api doc.
  docs/contributing/api.md
  libs/chatchat-server/chatchat/server/agent/graphs_factory/base_graph.py
  libs/chatchat-server/chatchat/server/agent/graphs_factory/plan_and_execute.py
Labels: size:S

#4891 Feature/tavily search tool
  libs/chatchat-server/chatchat/server/agent/tools_factory/search_internet.py
  libs/chatchat-server/chatchat/settings.py
Labels: size:XS

#4678 fix: milvus RPC error
  libs/chatchat-server/chatchat/settings.py
Labels: size:XS
