Repository chatchat-space/Langchain-Chatchat, pull requests merged in 2024-02, with the labels that each got.

#2919 修复es 知识库查询bug (#2848)
  server/knowledge_base/kb_service/es_kb_service.py
Labels: size:S

#2945 更新zhipuai请求方式
  README.md
  README_en.md
  README_ja.md
  configs/model_config.py.example
  configs/server_config.py.example
  img/qr_code_86.jpg
  img/qr_code_87.jpg
  img/qr_code_88.jpg
  img/qr_code_89.jpg
  requirements.txt
  requirements_api.txt
  server/knowledge_base/kb_service/milvus_kb_service.py
  server/model_workers/xinghuo.py
  server/model_workers/zhipu.py
Labels: size:M

#2949 增加对 `.htm` 扩展名的显式支持，以解决 `.htm` 格式网页可被上传但不被入库的问题
  server/knowledge_base/utils.py
Labels: size:XS

#2957 更新readme
  README.md
  README_en.md
  README_ja.md
  img/qr_code_89.jpg
  img/qr_code_90.png
  requirements.txt
  requirements_api.txt
  requirements_lite.txt
  requirements_webui.txt
Labels: size:S

#2960 requirements_webui.txt
  requirements_webui.txt
Labels: size:XS
