Repository chatchat-space/Langchain-Chatchat, pull requests merged in 2024-05, with the labels that each got.

#3912 修复zhipu-api向量化失败问题
  server/knowledge_base/kb_cache/faiss_cache.py
  server/model_workers/zhipu.py
Labels: size:M, lgtm

#3203 百川调用示例
  server/model_workers/baichuan.py
Labels: size:M

#3886 CICD github action build publish pypi、Release Tag
  .github/actions/poetry_setup/action.yml
  .github/workflows/_release.yml
  .github/workflows/_test_release.yml
  model-providers/pyproject.toml
  model-providers/tests/unit_test/conftest.py
  model-providers/tests/unit_tests/model_providers.yaml
  model-providers/tests/unit_tests/test_provider_manager_models.py
Labels: size:XL

#3943 一些agent数据处理的问题，model_runtime模块的说明文档
  chatchat-server/chatchat/server/agent/agent_factory/glm3_agent.py
  chatchat-server/chatchat/server/chat/chat.py
  model-providers/model_providers/core/model_runtime/README.md
  model-providers/model_providers/core/model_runtime/README_CN.md
  model-providers/model_providers/core/model_runtime/docs/en_US/images/index/image-20231210143654461.png
  model-providers/model_providers/core/model_runtime/docs/en_US/images/index/image-20231210144229650.png
  model-providers/model_providers/core/model_runtime/docs/en_US/images/index/image-20231210144814617.png
  model-providers/model_providers/core/model_runtime/docs/en_US/images/index/image-20231210151548521.png
  model-providers/model_providers/core/model_runtime/docs/en_US/images/index/image-20231210151628992.png
  model-providers/model_providers/core/model_runtime/docs/en_US/images/index/image-20231210165243632.png
  model-providers/model_providers/core/model_runtime/docs/en_US/images/index/img.png
  model-providers/model_providers/core/model_runtime/docs/en_US/provider_scale_out.md
  model-providers/model_providers/core/model_runtime/docs/zh_Hans/customizable_model_scale_out.md
  model-providers/model_providers/core/model_runtime/docs/zh_Hans/images/index/image-1.png
  model-providers/model_providers/core/model_runtime/docs/zh_Hans/images/index/image-2.png
  model-providers/model_providers/core/model_runtime/docs/zh_Hans/images/index/image-20231210143654461.png
  model-providers/model_providers/core/model_runtime/docs/zh_Hans/images/index/image-20231210144229650.png
  model-providers/model_providers/core/model_runtime/docs/zh_Hans/images/index/image-20231210144814617.png
  model-providers/model_providers/core/model_runtime/docs/zh_Hans/images/index/image-20231210151548521.png
  model-providers/model_providers/core/model_runtime/docs/zh_Hans/images/index/image-20231210151628992.png
  model-providers/model_providers/core/model_runtime/docs/zh_Hans/images/index/image-20231210165243632.png
  model-providers/model_providers/core/model_runtime/docs/zh_Hans/images/index/image-3.png
  model-providers/model_providers/core/model_runtime/docs/zh_Hans/images/index/image.png
  model-providers/model_providers/core/model_runtime/docs/zh_Hans/images/index/img.png
  model-providers/model_providers/core/model_runtime/docs/zh_Hans/predefined_model_scale_out.md
  model-providers/model_providers/core/model_runtime/docs/zh_Hans/provider_scale_out.md
Labels: size:L

#3944 更新 webui，支持 st.dialog
  chatchat-server/chatchat/configs/basic_config.py.example
  chatchat-server/chatchat/configs/prompt_config.py.example
  chatchat-server/chatchat/server/api_server/openai_routes.py
  chatchat-server/chatchat/server/api_server/server_app.py
  chatchat-server/chatchat/server/chat/chat.py
  chatchat-server/chatchat/server/utils.py
  chatchat-server/chatchat/webui.py
  chatchat-server/chatchat/webui_pages/dialogue/dialogue.py
  chatchat-server/chatchat/webui_pages/utils.py
  requirements.txt
Labels: size:XL

#3951 通过importlib，动态加载configs文件
  chatchat-server/chatchat/configs/__init__.py
  chatchat-server/chatchat/configs/model_providers.yaml.example
  chatchat-server/chatchat/server/knowledge_base/migrate.py
  chatchat-server/pyproject.toml
  requirements.txt
Labels: size:XL

#3979 [add]添加获取模型接口
  frontend/src/app/api/models/chatchat/route.ts
  frontend/src/app/settings/llm/ChatChat/index.tsx
  frontend/src/app/settings/llm/components/ModelSeletor.tsx
  frontend/src/features/ModelSwitchPanel/index.tsx
  frontend/src/locales/default/setting.ts
  frontend/src/services/_url.ts
  frontend/src/services/models.ts
  frontend/src/store/global/slices/settings/selectors/modelProvider.ts
  frontend/src/types/message/index.ts
  frontend/src/types/models.ts
  frontend/src/types/settings/modelProvider.ts
Labels: size:L

#4009 path traversal bug in api /knowledge_base/download_doc(#4008)
  server/knowledge_base/utils.py
Labels: size:XS

#4017 update "path traversal bug in api /knowledge_base/download_doc(#4008)…
  server/knowledge_base/utils.py
Labels: size:XS

#4029 replace Path.is_relative_to to make py38 compatible
  server/knowledge_base/utils.py
Labels: size:XS

#4048 fix: incorrect variable usage in update_doc_by_ids method
  server/knowledge_base/kb_service/base.py
Labels: size:S

#3873 Update 大模型应用技术原理.md
  knowledge_base/samples/content/llm/大模型应用技术原理.md
Labels: size:XS

#4085 feat:Added some documentation.
  libs/chatchat-server/README.md
  libs/chatchat-server/chatchat/configs/model_providers.yaml
  libs/model-providers/README.md
  libs/model-providers/model_providers.yaml
Labels: size:M
